apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic-router.fullname" . }}
  labels:
    {{- include "traffic-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 3333
      targetPort: 3333
      protocol: TCP
      name: idk # TODO: Figure out what this doess
    - port: 3443
      targetPort: 3443
      protocol: TCP
      name: https
  selector:
    {{- include "traffic-router.selectorLabels" . | nindent 4 }}
