apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic-portal.fullname" . }}
  labels:
    {{- include "traffic-portal.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "traffic-portal.selectorLabels" . | nindent 4 }}